name: dogma_codegen_polymer
version: 0.0.1
description: Code generation of Polymer elements for the Dogma libraries.
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://dogma-dart.github.io/
environment:
  sdk: '>=1.14.0-any <2.0.0'
dependencies:
  build: ^0.2.0
  dogma_convert:
    path: ../dogma-convert
  dogma_codegen:
    path: ../dogma-codegen
  dogma_codegen_model:
    path: ../dogma-codegen-model
  dogma_source_analyzer:
    path: ../dogma-source-analyzer
  logging: ^0.11.1+1
  polymer: ^1.0.0-rc.15
dev_dependencies:
  test: ^0.12.3+9
  dogma_codegen_test:
    path: ../dogma-codegen-test
